name: CI/CD Proyecto Mascotas

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # ===========================
  # JOB 1: INTEGRACIÓN CONTINUA
  # ===========================
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # Eliminamos la línea de 'cache' para evitar el error del lock file

      # ---------- BACKEND ----------
      - name: Instalar y Probar Backend
        working-directory: backend_mascotas
        run: |
          npm install
          npm test --if-present

      # ---------- FRONTEND ----------
      - name: Instalar y Build Frontend
        working-directory: mascotas_fronted
        run: |
          npm install
          npm run build

      - name: Subir artefacto de build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  # ===========================
  # ETAPA 2: DESPLIEGUE FRONTEND (GitHub Pages)
  # ===========================
  deploy_frontend:
    needs: ci
    if: github.event_name == 'push' # Solo despliega si es un push a main
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Descargar build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  # ===========================
  # ETAPA 3: DOCKER BACKEND
  # ===========================
  build_and_push_backend:
    needs: ci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-mascotas-backend:latest